name: MLOps Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install scikit-learn xgboost joblib fastapi uvicorn
    - name: Train model
      run: python train.py
    - name: Evaluate model
      run: python evaluate.py
    - name: Register model
      run: python register_model.py
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Adding Model"
        title: "Adding Model"
        body: "Automated removal of specified .tf files."
        branch: "test"
        delete-branch: true
        base: "main" # Target branch to merge changes into
        token: ${{ secrets.pat }}
