name: MLOps Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install scikit-learn xgboost joblib fastapi uvicorn
    - name: Train model
      run: python train.py
    - name: Evaluate model
      run: python evaluate.py
    - name: Register model
      run: python register_model.py
    - name: Commit model to registry
      run: |
        git config --global user.email "jchilu15@gmail.com"
        git config --global user.name "jLuPSP"
        git add registry/
        git commit -m "Register model [CI]"
        git push
